# Generated by Django 5.2.3 on 2025-08-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_product_category_product_created_at_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
