# Generated by Django 5.2.3 on 2025-07-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Customer'), ('shopkeeper', 'Shop Owner'), ('admin', 'Admin')], default='user', max_length=10),
        ),
    ]
