# Generated by Django 5.2.3 on 2025-07-16 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Customer'), ('shop', 'Shop Owner'), ('admin', 'Admin')], default='user', max_length=10),
        ),
    ]
